---
title: "EDUC 645 Assignments"
site: distill::distill_website
output:
  html_document:
    toc: TRUE
    toc_depth: 3
    toc_float: TRUE
    theme: cosmo
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 1. General Guidelines

The goal of the assignments is to practice the concepts and vocabulary we have been modeling in class and implement some of the techniques we have discussed.

You may work on your own or collaborate with 1 or 2 partners (maximum of 3 per group). Please make sure that you engage in a full, fair and mutually-agreeable collaboration if you do choose to collaborate. If you do collaborate, you should plan, execute, and write-up your analyses together, not simply divide the work. Please make sure to indicate clearly when your work is joint and any other individual or resource (outside of class material) you consulted in your responses. Full requirements for  assignments, information on grading, and the late submission policy are discussed in the syllabus.

## 2. Submission format

For each of the 4 assignments and the final project, you are required to submit 2 files:  

 * .doc, .html, or .pdf file with your typed responses to the problems and any tables and figures you produce. 
   
 * The .Rmd or .R file that you used to render the tables and figures in the above doc/html/pdf file. 

## 3. Assignments details

### 3.1. Assignment 1 (Logistic regression)

*To be added*

<!-- Objectives: -->

<!--  - Using Logistic regression model to estimate a relationship where the dependent variable is dichotomous -->
<!--  - Interpret and report the results and make statistic inference from the estimated parameters -->

<!-- Deadline: TBD -->

<!-- Assignment description: [assignment1.html](./assignments/assignment01.html) -->

<!-- Dataset: [nscs.csv](./data/nscs.csv) -->

<!-- Key: [doc file]; [R script] -->

### 3.2. Assignment 2 (Poisson regression)

*To be added*

<!-- Objectives: -->

<!--  - Using Poisson regression model to estimate a relationship where the dependent variable is a Poisson random variable -->
<!--  - Interpret and report the results and make statistic inference from the estimated parameters -->

<!-- Deadline: TBD -->

<!-- Assignment description: [assignment2.html](./assignments/assignment02.html) -->

<!-- Dataset: [ah_smoke.csv](./data/ah_smoke.csv); [fsi.csv](./data/fsi.csv) -->

<!-- Key: [doc file]; [R script] -->

### 3.3. Assignment 3 (Nested data)

*To be added*

<!-- Objectives: -->

<!--  - Using mixed-effects model to estimate a relationship when the clustering nature of data needs to be addressed -->
<!--  - Interpret and report the results and make statistic inference from the estimated parameters -->

<!-- Deadline: TBD -->

<!-- Assignment description: [assignment3.html](./assignments/assignment03.html) -->

<!-- Dataset: [gpa.csv](./data/gpa.csv) -->

<!-- Key: [doc file]; [R script] -->

### 3.4. Assignment 4 (Reliability in measurement)

*To be added*

<!-- Objectives: -->

<!--  -  -->
<!--  -  -->

<!-- Deadline: TBD -->

<!-- Assignment description:  -->

<!-- Dataset: [fsi.csv](./data/fsi.csv) -->

<!-- Key: [doc file]; [R script] -->

<!-- ### 3.5. Final Project -->

<!-- Objectives: -->

<!--  -  -->
<!--  -  -->

<!-- Deadline: TBD -->

<!-- Assignment description: [final.html](./assignments/final.html) -->

<!-- Datasets: [add_health.csv](./data/add_health.csv); [fsi.csv](./data/fsi.csv) -->

<!-- Key: [doc file]; [R script] -->








