---
title: "EDUC 645 (EDUC 610L): Applied Statistics in Education and Human Services III"
subtitle: "College of Education, University of Oregon"

site: distill::distill_website
output:
  html_document:
    toc: TRUE
    toc_depth: 3
    toc_float: TRUE
    theme: cosmo
    
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Course Overview

This course is the third in a sequence intended to provide a toolkit of statistical concepts, methods, and their implementation to producers of applied research in education, human services, and other social sciences. The course is organized around the principle that research design and analysis depends on researchers’ substantive questions and the data they have available to address these questions. In this intermediate level course, students will learn about and practice using analytic models and strategies that are suitable for examining data that have (a) a dichotomous outcome variable, (b) a count outcome variable, (c) a nested structure, and/or (d) missing values. Students will also learn (e) when and how to estimate internal consistency reliability. The course seeks to blend a conceptual, mathematical, and applied understanding of introductory statistical concepts. Students will employ these statistical tools in a variety of applications, with a particular emphasis on strategies to generate research products relevant to culturally and linguistically diverse communities. At the core of our pedagogical approach is the belief that students learn statistical analysis by doing statistical analysis. 

*EDUC 643 (or a similar intermediate statistics course) is a pre-requisite as is a basic familiarity with a statistical programming language (preferably R).*  

# Meeting Time and Location
Tuesdays and Thursdays, 5:00pm–6:20pm

HEDCO 142

# Instructor 

* Nicholas J. Parr, PhD, MPH (he/him/his); Email: nparr2@uoregon.edu (preferred); Office hour: by appointment

# GTFs

* Havisha (Havi) Khurana (she/her/hers); Email: havishak@uoregon.edu (preferred); Office hour: by appointment

* Brittany Spinner (she/her/hers); Email: bspinner@uoregon.edu (preferred); Office hour: by appointment  

* Errol Kaylor (he/him/his); Email: errolk@uoregon.edu (preferred); Office hour: by appointment