---
title: "EDUC 645 Schedule"
site: distill::distill_website
output:
  html_document:
    toc: TRUE
    toc_depth: 3
    toc_float: TRUE
    theme: cosmo
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Unit 1: Logistic Regression

**Learning Objectives:** 

- Understand the linear probability model and discuss its limitations

- Understand and differentiate the concepts of probability, odds, and logit

- Learn how to use the logistic regression model with continuous and categorical predictors and interpret the model parameters and inference for model parameters

- Apply logistic regression model with an interaction between a continuous and categorical predictor, how to interpret the model parameters, and inference for model parameters

- Apply glm function in R to fit the logistic regression model

- Discuss the predictive power, model fit, and diagnostics for a logistic regression model

**Readings**:

 *
 * Fawcett, T. (2006). An introduction to ROC analysis. *Pattern Recognition Letters*, 27(8), 861-874.[https://doi.org/10.1016/j.patrec.2005.10.010](https://www.sciencedirect.com/science/article/abs/pii/S016786550500303X)

**Lecture**:

 * Lecture slides: [html](./slides/EDUC645_log_regression.html)
 * Dataset: [principal.csv](./data/principal.csv)

**Assignment**:

 * Assignment description: [assignment1.html](./assignments/assignment1.html)
 * Dataset: [nscs.csv](./data/nscs.csv)

## Unit 2: Poisson Regression

**Learning Objectives:** 

- Introduce regression models for analyzing count and rates

-	Describe situations which merit the use of Poisson regression

-	State the assumptions about rates in Poisson regression

- Introduce poisson regression model with continuous and categorical predictors, and how to interpret the model parameters and inference for model parameters

- Introduce the poisson regression model with an interaction between a continuous and categorical predictor, how to interpret the model parameters, and inference for model parameters

- Learn how to apply the glm function in R to fit the poisson regression model

- Discuss dispersion, model fit, and diagnostics for a poisson regression model

**Readings**: 

 * 
 * Coxe, S., West, S. G., & Aiken, L. S. (2009). The analysis of count data: A gentle introduction to Poisson regression and its alternatives. *Journal of Personality Assessment*, 91(2), 121-136. [https://doi.org/10.1080/00223890802634175](https://doi-org.libproxy.uoregon.edu/10.1080/00223890802634175)
 
**Lecture**:

 * Lecture slides: [html](./slides/EDUC645_poisson_regression.html)
 * Dataset: [ceps_sch.csv](./data/ceps_sch.csv)

**Assignment**:

 * Assignment description: [assignment2.html](./assignments/assignment2.html)
 * Dataset: [ah_smoke.csv](./data/ah_smoke.csv)


## Unit 3: Introduction to Nested Data

**Learning Objectives:** 

- Introduce the nested data structure (two-level, e.g., repeated measures within individuals, students within schools)

- Students will be able to understand and explain what nesting/clustering means

- Demonstrate varying intercepts and slopes across clusters. Using a dataset, students/instructors can fit the same regression model independently for each cluster and create a table of intercepts and slopes across clusters

- Students will understand what it means for intercepts and slopes to vary across clusters

- Develop/discuss the notion that regression coefficients may vary across different clusters

- Develop the concept of **fixed-effects** as the aggregation of the different intercepts and slopes by taking an average of varying intercept and slopes across clusters

- Develop the concept of **random effects** as the difference between cluster-specific intercept and slope and their averages across clusters

- Develop the concept of the covariance matrix of **random-effects**

- Discuss the implications of ignoring the variance of random-effects in terms of the inference for fixed-effects and statistical power

- Introduce the random intercept-only model, its estimation through the R lmer package, interpret the model parameters and align them with the earlier discussion of fixed-effects
and random-effects.

- Introduce the intra-class correlation as a measure of within-cluster dependency, and how to use it to decide whether one needs to use multilevel modeling

- Finish by emphasizing that this is a very brief introduction of nested data and refer students to the multilevel modeling sequence for a comprehensive treatment of the
subject

- *Time permitting*: Discuss alternatives to multilevel modeling of nested data

**Readings**: 

**Lecture**:

 * Lecture slides: [html](./slides/EDUC645_nested_data.html)
 * Dataset: [seda.csv](./data/seda.csv) and [portugal.csv](./data/portugal.csv)

**Assignment**:

 * Assignment description: [assignment3.html](./assignments/assignment3.html)
 * Dataset: [gpa.csv](./data/gpa.csv) / [gpa_above.csv](./data/gpa_above.csv)


## Unit 4: Introduction to Measurement and Assessment

**Learning Objectives:** 

- Introduction to the concept of reliability

- Understand the assumption of underlying shared construct for a set of items in surveys with aggregated scores across items

- Demonstrate how to compute and interpret Cronbach's alpha, and emphasize the strong underlying assumptions

**Readings**: 

**Lecture**:

 * Lecture slides: [html](./slides/EDUC645_measure_assess.html)
 * Dataset:
 
**Assignment**:

 * Assignment description: [assignment4.html](./assignments/assignment4.html)
 * Dataset: 

## Unit 5: Data Cleaning and Handling Missing Data

**Learning Objectives:** 

- Students should be ready to talk about the concept of model-based imputation as earlier lectures in the sequence covered linear regression and logistic regression

- Introduce the missing data mechanisms (MCAR, MAR, MNAR)

- Introduce the concepts of the listwise deletion and pairwise deletion and their potential limitations

- Introduce the single-imputation methods (mean, regression, and stochastic regression imputation)

- Introduce the "missing-value-dummy" method (Cohen) and some issues with this approach

- Introduce the conceptual steps for the multiple-imputation

- Introduce the mice package in R and how to implement multiple-imputation for fitting a regression model to a data set with missing values


**Readings**: 
  
  * Raghunathan, T. E. (2004). What do we do with missing data? Some options for analysis of incomplete data. *Annual Review of Public Health*, 25(1), 99-117. [https://doi.org/10.1146/annurev.publhealth.25.102802.124410](https://pubmed.ncbi.nlm.nih.gov/15015914/)
  * Baraldi, A. N., & Enders, C. K. (2010). An introduction to modern missing data analyses. *Journal of School Psychology*, 48(1), 5-37. [https://doi.org/10.1016/j.jsp.2009.10.001](https://pubmed.ncbi.nlm.nih.gov/20006986/)

**Lecture**:

 * Lecture slides: [html](./slides/EDUC645_cleaning_missing.html)
 * Dataset: [galo.csv](./data/galo.csv)
 
**Assignment**:

No assignment for this unit.

**Final Project**:

 * Final project description: [final.html](./assignments/final.html)
 * Dataset: 

