---
title: "EDUC 645 (EDUC 610L) Syllabus"
site: distill::distill_website
output:
  html_document:
    toc: TRUE
    toc_depth: 3
    toc_float: TRUE
    theme: cosmo
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

# Indigenous Recognition Statement
The University of Oregon is located on Kalapuya Ilihi, the traditional indigenous homeland of the Kalapuya people. Today, descendants are citizens of the Confederated Tribes of the Grand Ronde Community of Oregon and the Confederated Tribes of Siletz Indians of Oregon, and they continue to make important contributions in their communities, at UO, and across the land we now refer to as Oregon. 

# I. General Course Information
**EDUC 645 (EDUC 610L): Applied Statistics in Education and Human Services III (3 credits) - Spring 2024 (31569)**

*Meeting Time and Location*

Tuesdays and Thursdays, 5:00pm–6:20pm

HEDCO 142

*Instructor*: 

* Nicholas J. Parr, PhD, MPH (he/him/his); Email: nparr2@uoregon.edu (preferred); Office hour: by appointment

*GTFs*:

* Havisha (Havi) Khurana (she/her/hers); Email: havishak@uoregon.edu (preferred); Office hour: by appointment

* Brittany Spinner (she/her/hers); Email: bspinner@uoregon.edu (preferred); Office hour: by appointment  

* Errol Kaylor (he/him/his); Email: errolk@uoregon.edu (preferred); Office hour: by appointment

# II. Course Overview
This course is the third in a sequence intended to provide a toolkit of statistical concepts, methods, and their implementation to producers of applied research in education, human services, and other social sciences. The course is organized around the principle that research design depends in part on researchers’ substantive questions and their quantitative data available to address these questions. In this upper-level introductory course, students will learn about and practice using analytic models and strategies that are suitable for examining data that have (a) a dichotomous outcome variable, (b) a count outcome variable, (c) a nested structure, and/or (d) missing values; students will also learn about when and how to estimate (e) internal consistency reliability for research purposes. The course seeks to blend a conceptual, mathematical, and applied understanding of introductory statistical concepts. At the core of our pedagogical approach is the belief that students learn statistical analysis by doing statistical analysis. 

*EDUC 643 (or a similar intermediate statistics course) is a pre-requisite as is a basic familiarity with a statistical programming language (preferably R).*  

# III. Student Learning Outcomes
By the end of this term, it is expected that students will be able to: 

1. Determine when it is appropriate to use logistic regression or Poisson regression analyses and analyses that account for nested data in education and human services research.  

2. Conduct and interpret basic logistic and Poisson regression analyses and analyses that account for nested data.  

3. Describe the assumptions of logistic and Poisson regression analyses and analyses for nested data, and test analytic models for the extent to which they satisfy the models’ assumptions.  

4. Understand the role of reliability in linear models and calculate internal consistency coefficients.   

5. Explain common mechanisms of missingness and the applications and limitations of different methods for handling missing data.  

6. Assess missing data characteristics and implement multiple imputation to handle missing data.  

7. Perform all analyses using an object-oriented, open-source programming language. 

# Textbooks, Reading Materials, and Software
## Textbooks
The following text and reading materials are required:

* Roback, P., & Legler, J. (2021). Beyond multiple linear regression: Applied generalized linear models and multilevel models in R (1st ed.). CRC Press. https://bookdown.org/roback/bookdown-BeyondMLR/ 

* Dunn, T. J., Baguley, T., & Brunsden V. (2014). From alpha to omega: A practical solution to the pervasive problem of internal consistency estimation. British Journal of Psychology, 105, 399–412. https://doi.org/10.1111/bjop.12046  

* Little, T. D., Jorgensen, T. D., Lang, K. M., & Moore, W. G. (2013). On the joys of missing data. Journal of Pediatric Psychology, 39(2), 151–162. https://doi.org/10.1093/jpepsy/jst048 

We will primarily be referring to chapters in Roback and Legler’s [Beyond Multiple Linear Regression ](https://bookdown.org/roback/bookdown-BeyondMLR/) (**BMLR**), which is available for free online.

## Supplemental reading materials 
Further readings will be provided in the form of peer-reviewed journal articles. Links to these papers will be provided in the schedule. 

## R and RStudio
Students must have the latest version of R, which can be downloaded [here](https://ftp.osuosl.org/pub/cran/). It is strongly recommended that students also download the RStudio GUI, available [here](https://www.rstudio.com/products/rstudio/download/#download). Both are free.

### Resources for R and RStudio

While this course teaches you how to effectively use R and RStudio to conduct analyses, one of the key skills required to use R is the ability to find answers on your own. Many common questions or problems are either available on blogs or have been asked and answered in discussion forums already. Finding and deciphering those answers is an important skill you should seek to hone. *It is impossible to remember all programming commands!* 

Here are some sites where you can find the answers to many R questions and learn new tricks:

 - [_YaRrr, the Pirate's Guide to R_](https://bookdown.org/ndphillips/YaRrr/) by Nathaniel Phillips
 - [_R for Data Science_](https://r4ds.had.co.nz/) by Hadley Wickham
 - [_R Cookbook_](http://www.cookbook-r.com/) by Winston Chang
 - [_An Introduction to Statistical Learning_](http://www-bcf.usc.edu/~gareth/ISL) by Gareth James, Daniela Witten, Trevor Hastie and Robert Tibshirani
 - [Cheat Sheets](https://www.rstudio.com/resources/cheatsheets) 
 - [Quick-R](https://www.statmethods.net) 
 - [StackOverflow](https://stackoverflow.com/questions/tagged/r)
 - [Stack Exchange](https://stats.stackexchange.com)

# IV. Weekly Schedule of Topics, Assignments, and Readings 

See [here](./schedule.html). 

# V. Grading Components and Criteria 
Grades will be assigned in accordance with the College of Education grading requirements. Grades are criterion-referenced; that is, each student’s performance is graded according to the extent to which they meet the course learning and performance criteria and exhibit individual learning. You can check your assignment grades and points on Canvas.  

The due dates for course assignments and the final are posted [here](./assignments.html). Late work can receive a grade no higher than a B+ unless an extension has been requested and approved by the instructor **before** the assignment is due. Assignments submitted after the last day of class will be given no credit.  

Final grades will be based on the following components:

- Quizzes: 15% (3 quizzes at 5% each)
- Assignments: 60% (3 assignments at 20% each)
- Final Project: 25%

| Grade | Percentage   | Grade | Percentage   |
|-------|--------------|-------|--------------|
| A+    | >_ 98%       | C+    | 77% to < 80% |
| A     | 94% to < 98% | C     | 73% to < 77% |
| A-    | 90% to < 94% | C-    | 70% to < 73% |
| B+    | 87% to < 90% | D     | 60% to < 70% |
| B     | 83% to < 87% | F     | < 60%        |
| B-    | 80% to < 83% |       |              |

## Quizzes
Each of the three units will include an open-book/open-note quiz taken on Canvas. Quizzes will cover core concepts discussed in the initial lectures of each unit. 

## Assignments
The goal of the assignments is to practice the concepts and vocabulary we have been modeling in class and implement some of the techniques we have discussed. Each assignment has an associated data source, short codebook, and detailed instructions for the required data and analytic tasks. You may work on your own or collaborate with up to two (2) partners. Please make sure that you engage in a full, fair, and mutually-agreeable collaboration if you do choose to collaborate. If you do collaborate, you should plan, execute, and write-up your analyses together; do not simply divide up the work. Please make sure to indicate clearly when your work is joint and any other individual or resource (outside of class material) you consulted in your responses. Further assignment details are available on the course website. Further assignment details are available [here](./assignments.html). Assignments will be evaluated based on students’ performance in completing the assignment tasks, showing their work, and in demonstrating their understanding of the course concepts and terminology.

## Final
The final assignment involves a more extended application of methods covered in this course. Instructions for the final assignment will be provided during Week 9 and listed [here](./assignments.html).

# VI. Statement of How Requirements Differ for Undergraduate and Graduate Students 

This course does not have an undergraduate section. 

# VII. Role of Graduate Employees 

If you are concurrently taking any courses with the graduate employee (GE) assigned to this course, please let the instructor know. The GE will not be involved with any review of assignments for students in this course who are taking other courses concurrently. 

# VIII. Student Engagement Inventory
Graduate students are expected to perform work of high quality and quantity, typically with forty hours of student engagement for each student credit hour. For this course, the following table shows the number of hours a typical student would expect to spend in each of the following activities:

| Educational activity   | Hours   | Explanatory comments
|------------------------|---------|---------------------------------
| Class attendance       | 30      | Three hours per week over 10 weeks
| Class reading and prep | 30      | Includes reading and review of slides
| Assignments            | 24      | Three assignments taking 8 hours each (on avg.)
| Quizzes                | 5       | 1 hour per quiz (40 min preparation, 20 min completing quiz)
| Lab attendance         | 10      | One hour-long lab per week over 10 weeks    
| Final project          | 21      | Includes familiarization with data, data analysis, preparation of graphics and writing
| **Total hours**        | **120** | 

# IX. Attendance and Absence Guidelines 

Attendance is required. In-person attendance at our scheduled class meetings is expected and is integral to success in the course. In the case of unavoidable absence, students must inform the instructor as early as possible to discuss make-up work. If you need accommodation related to disability, you can request those by working with the Accessible Education Center (https://aec.uoregon.edu). 

# X. Expected Classroom Behavior 

Minimally, we follow the Golden Rule of treating others as we wish to be treated. We must also attend to equity concerns and understand that each of us has a unique experience and we vary in our values and expectations. 

# XI. Diversity, Equity and Inclusion 

It is the policy of the University of Oregon to support and value equity and diversity and to provide inclusive learning environments for all students. To do so requires that we:  

* respect the dignity and essential worth of all individuals.  

* promote a culture of respect throughout the University community.  

* respect the privacy, property, and freedom of others.  

* reject bigotry, discrimination, violence, or intimidation of any kind.  

* practice personal and academic integrity and expect it from others.  

* promote the diversity of opinions, ideas and backgrounds which is the lifeblood of the university. 

In this course, class discussions, projects/activities and assignments will challenge students to think critically about and be sensitive to the influence, and intersections, of race, ethnicity, nationality, documentation, language, religion, gender, socioeconomic background, physical and cognitive ability, sexual orientation, and other cultural identities and experiences. Students will be encouraged to develop or expand their respect and understanding of such differences.

Maintaining an inclusive classroom environment where all students feel able to talk about their cultural identities and experiences, ideas, beliefs, and values will not only be my responsibility, but the responsibility of each class member as well. Behavior that disregards or diminishes another student will not be permitted for any reason. This means that no racist, ableist, transphobic, xenophobic, chauvinistic or otherwise derogatory comments will be allowed. It also means that students must pay attention and listen respectfully to each other’s comments.

# XII. Using Pronouns and Personal Preference 

The College of Education is always working to include and engage everyone. One way we can do this is to share your pronouns, or the words you want to be called when people aren’t using your name. Like names, pronouns are an important part of how we identify that deserves to be respected. And we recognize that assuming someone’s gender can be hurtful, especially to members of our community who are transgender, genderqueer, or non-binary. As a community, we are all learning together about the importance of pronouns and being better allies to the trans community on campus. Please discuss the pronouns you wish to be used with your professor to help them be aware of how to address you respectfully. Please visit this university website for more information: https://studentlife.uoregon.edu/pronouns

# XIII. Accessible Education

The University of Oregon is working to create inclusive learning environments. Please notify me if there are aspects of the instruction or design of this course that result in disability-related barriers to your participation. Participation includes access to lectures, web-based information, in-class activities, and exams. The Accessible Education Center (http://aec.uoregon.edu/) works with students to provide an instructor notification letter that outlines accommodations and adjustments to class design that will enable better access. Contact the Accessible Education Center in 360 Oregon Hall at 541-346-1155 or uoaec@uoregon.edu for assistance with access or disability-related questions or concerns.

# XIV. Accommodation for Religious Observances 

The university makes reasonable accommodations, upon request, for students who are unable to attend a class for religious obligations or observance reasons, in accordance with the university discrimination policy which says “Any student who, because of religious beliefs, is unable to attend classes on a particular day shall be excused from attendance requirements and from any examination or other assignment on that day. The student shall make up the examination or other assignment missed because of the absence.” To request accommodations for this course for religious observance, visit the Office of the Registrar's website (https://registrar.uoregon.edu/calendars/religious-observances) and complete and submit to the instructor the “Student Religious Accommodation Request” form prior to the end of the second week of the term.

# XV. Mental Health and Wellness 

Life at college can be very complicated. Students often feel overwhelmed or stressed, experience anxiety or depression, struggle with relationships, or just need help navigating challenges in their life. If you're facing such challenges, you don't need to handle them on your own--there's help and support on campus. 

As your instructor if I believe you may need additional support, I will express my concerns, the reasons for them, and refer you to resources that might be helpful. It is not my intention to know the details of what might be bothering you, but simply to let you know I care and that help is available. Getting help is a courageous thing to do—for yourself and those you care about.

University Health Services help students cope with difficult emotions and life stressors. If you need general resources on coping with stress or want to talk with another student who has been in the same place as you, visit the Duck Nest (located in the EMU on the ground floor) and get help from one of the specially trained Peer Wellness Advocates. Find out more at https://health.uoregon.edu/ducknest. 

University Counseling Services (UCS) has a team of dedicated staff members to support you with your concerns, many of whom can provide identity-based support. All clinical services are free and confidential. Find out more at https://counseling.uoregon.edu/ or by calling 541-346-3227 (anytime UCS is closed, the After-Hours Support and Crisis Line is available by calling this same number).

# XVI. Basic Needs 

Any student who has difficulty affording groceries or accessing sufficient food to eat every day, or who lacks a safe and stable place to live and believes this may affect their performance in the course is urged to contact the Dean of Students Office (346-3216, 164 Oregon Hall) for support. 

This UO webpage includes resources for food, housing, healthcare, childcare, transportation, technology, finances, and legal support: https://blogs.uoregon.edu/basicneeds/food/  If your need is urgent, please contact the Care and Advocacy Program by calling 541-346-3216, filling out the [Community Care and Support form](https://cm.maxient.com/reportingform.php?UnivofOregon&layout_id=1), or by [scheduling an appointment with an advocate](https://outlook.office365.com/owa/calendar/CareandAdvocacyProgram@uoregon.edu/bookings/). 

# XVII. Respect for Diversity 

You can expect to be treated with respect in this course. Both students and your instructor(s) enter with many identities, backgrounds, and beliefs. Students of all racial identities, ethnicities, and genders, gender identities, gender expressions, national origins, religious affiliations, sexual orientation, citizenship statuses, ability and other visible and non-visible differences belong in and contribute to this class and this discipline. All students are expected to contribute to a respectful, welcoming and inclusive environment for every member of the class. 

Class rosters are provided to instructors with students’ legal names. Please let me know if the name or pronouns I have for you are not accurate. It is important to me to address you properly. 

Please let me know if aspects of the instruction, course design, or class activities undermine these principles in any way. You may also notify the (Home Department) at (contact information). For additional assistance and resources, you may also consider contacting the [Division of Equity and Inclusion through their website](http://inclusion.uoregon.edu/) or by phone (at 541-346-3175), or the [Center for Multicultural Academic Excellence through their website](https://inclusion.uoregon.edu/center-multicultural-academic-excellence-cmae) or by phone (at 541-346-3479). 

# XVII. Academic Integrity

The University Student Conduct Code (available at conduct.uoregon.edu) defines academic misconduct. Students are prohibited from committing or attempting to commit any act that constitutes academic misconduct. By way of example, students should not give or receive (or attempt to give or receive) unauthorized help on assignments or examinations without express permission from the instructor. Students should properly acknowledge and document all sources of information (e.g., quotations, paraphrases, ideas) and use only the sources and resources authorized by the instructor. If there is any question about whether an act constitutes academic misconduct, it is the students’ obligation to clarify the question with the instructor before committing or attempting to commit the act. Additional information about a common form of academic misconduct, plagiarism, is available at https://researchguides.uoregon.edu/citing-plagiarism.

# XIX. Mandatory Reporter Status 

I am an assisting employee. For information about my reporting obligations as an employee, please see [Employee Reporting Obligations](https://investigations.uoregon.edu/employee-responsibilities#employee-obligations) on the Office of Investigations and Civil Rights Compliance (OICRC) website. Students experiencing any form of prohibited discrimination or harassment, including sex or gender-based violence, may seek information and resources at safe.uoregon.edu, respect.uoregon.edu, or investigations.uoregon.edu or contact the non-confidential Title IX office/Office of Civil Rights Compliance (541-346-3123), or Dean of Students offices (541-346-3216), or call the 24-7 hotline 541-346-SAFE for help. I am also a mandatory reporter of child abuse. Please find more information at [Mandatory Reporting of Child Abuse and Neglect](https://hr.uoregon.edu/policies-leaves/general-information/mandatory-reporting-child-abuse-and-neglect).

# XX. Academic Disruption due to Campus Emergency 

In the event of a campus emergency that disrupts academic activities, course requirements, deadlines, and grading percentages are subject to change. Information about changes in this course will be communicated as soon as possible by email, and on Canvas. If we are not able to meet face-to-face, students should immediately log onto Canvas and read any announcements and/or access alternative assignments. Students are also encouraged to continue the readings and other assignments as outlined in this syllabus or subsequent syllabi.

# XXI. Inclement Weather 

It is generally expected that class will meet unless the University is officially closed for inclement weather. If it becomes necessary to cancel class while the University remains open, this will be announced on Canvas and by email. Updates on inclement weather and closure are also communicated in other ways described here: https://hr.uoregon.edu/about-hr/campus-notifications/inclement-weather/inclement-weather-immediate-updates

# XXII. Conflict Resolution  

Several options, both informal and formal, are available to resolve conflicts for students who believe they have been subjected to or have witnessed bias, unfairness, or other improper treatment.  

It is important to exhaust the administrative remedies available to you including discussing the conflict with the specific individual, contacting the Department Head, or within the College of Education, fall term you can contact the Associate Dean for Academic Affairs, Sylvia Thompson, (541) 346-2483, sthomps5@uoregon.edu. Outside the College, you can contact:  

* UO Bias Response Team: 346-3216 http://bias.uoregon.edu/whatbrt.htm  

* Conflict Resolution Services 346-3216 http://studentlife.uoregon.edu/support 

* Affirmative Action and Equal Opportunity: 346-3123 http://aaeo.uoregon.edu/ 

# XXIII. Grievance Policy 

A student or group of students of the College of Education may appeal decisions or actions pertaining to admissions, programs, evaluation of performance and program retention and completion. Students who decide to file a grievance should follow University student grievance procedures (https://policies.uoregon.edu/grievance-procedures) and/or consult with the College Associate Dean for Academic Affairs (Sylvia Thompson, (541) 346-2483  sthomps5@uoregon.edu). 

# XXIV. Course Incomplete Policy 

Students are expected to be familiar with university policy regarding grades of “incomplete” and the timeline for completion. For details on the policy and procedures regarding incompletes, Please see: https://education.uoregon.edu/academics/incompletes-courses 

# XXV. Reporting Title IX Experiences 

Any student who has experienced sexual assault, relationship violence, sex or gender-based bullying, stalking, and/or sexual harassment may seek resources and help at safe.uoregon.edu. To get help by phone, a student can also call either the UO’s 24-hour hotline at 541-346-7244 [SAFE], or the non-confidential Title IX Coordinator at 541-346-8136. From the SAFE website, students may also connect to Callisto, a confidential, third-party reporting site that is not a part of the university.  

Students experiencing any other form of prohibited discrimination or harassment can find information at https://respect.uoregon.edu/ or https://aaeo.uoregon.edu/ or contact the non-confidential AAEO office at 541-346-3123 or the Dean of Students Office at 541-346-3216 for help. As UO policy has different reporting requirements based on the nature of the reported harassment or discrimination, additional information about reporting requirements for discrimination or harassment unrelated to sexual assault, relationship violence, sex or gender based bullying, stalking, and/or sexual harassment is available at http://aaeo.uoregon.edu/content/discrimination-harassment  

Specific details about confidentiality of information and reporting obligations of employees can be found at https://titleix.uoregon.edu.  