---
title: "Course Overview"
subtitle: "EDUC 645"
#date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  xaringan::moon_reader:
    css: ['default', 'uo', 'ki-fonts', 'my_custom.css', 'xaringanthemer.css']
    # self_contained: true
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
editor_options: 
  
  chunk_output_type: console
---

```{R, setup, include = F}
library(pacman)
p_load(here, tidyverse, xaringan, knitr, kableExtra, haven, broom, xaringanthemer, foreign)

i_am("slides/EDUC645_1_intro.rmd")
red_pink <- "#e64173"
turquoise = "#20B2AA"
orange = "#FFA500"
red = "#fb6107"
blue = "#3b3b9a"
green = "#004F39"
grey_light = "#B3B3B3"
grey_mid = "#7F7F7F"
grey_dark = "grey20"
purple = "#6A5ACD"
slate = "#314f4f"
extra_css <- list(
  ".red"   = list(color = "red"),
  ".blue"  =list(color = "blue"),
  ".red-pink" = list(color= "#e64173"),
  ".green" = list(color = "#004F39"),
  ".gray" = list(color= "#B3B3B3"),
  ".purple" = list(color = "purple"),
  ".small" = list("font-size" = "90%"),
  ".large" = list("font-size" = "120%"),
  ".tiny" = list("font-size" = "70%"),
  ".tiny2" = list("font-size" = "50%"))
write_extra_css(css = extra_css, outfile = "my_custom.css")

# Knitr options
opts_chunk$set(
  comment = "#>",
  fig.align = "center",
  fig.height = 5,
  fig.width = 8,
  warning = F,
  message = F
)
```

# Goals of EDUC quant sequence

- Develop the basic quantitative skills necessary to conduct applied data analysis


--
 + The full-year sequence (EDUC 641 $\rightarrow$ EDUC 643 $\rightarrow$ **EDUC 645**) covers the foundations of statistics and data science to prepare you to make valuable contributions to a research team
 + Not all the skills you'll need are covered, particularly for those interested in analysis-heavy positions, or becoming an applied quantitative doctoral-level researcher


--
- Understand the (in)appropriate application of those skills


--
 + "Building a toolbox, not a cookbook"
 + Evaluate the credibility of published research
 + Understand the capabilities, limitations, and misuses of quantitative analysis


--
.small[.blue[This is an entirely re-designed and modernized quantitative sequence for the COE. We welcome your feedback! Given the newness of these three courses, there are likely to be shortcomings. We are committed to solving them as they arise, but we ask for your grace in allowing us to do so. In the end, we think this will be a better experience for you and your future program-mates.]]

---
# EDUC sequence principles

Courses in the EDUC methods sequence share the following principles:


--
- Analysis follows research design, which emerges from substantive questions


--
- Students learn statistical analysis by doing statistical analysis


--
- Create an inclusive, supportive environment in which we learn from each other


--
- Balance support and academic stretch across a variety of levels of prior experience and comfort with quantitative analysis


--
**.small[.blue[We started with an assumption of no prior background in mathematics, programming, statistics or research]]**


---
# EDUC sequence assumptions

We assume that you enter this course (EDUC 645) with the ability to:


--
- Create an RStudio project, read in a dataset in csv format, filter rows, select columns, understand structure of data, recode variables, assess missingness, and calculate summary statistics for continuous and categorical variables in the R programming language


--
- Create simple visualizations describing categorical and continuous variables, and their relationships with each other in R


--
- State a quantitative research question and its corresponding null hypothesis


--
- Articulate the conceptual basis for a null-hypothesis significance test


--
- Conduct a one-sample $t$-test and fit a bivariate Ordinary Least Squares (OLS) regression



--
See [EDUC 641 data management guide](https://daviddliebowitz.github.io/EDUC641_22F/data_management.html) for data management pointers


---
# Goals of EDUC 645

In this intermediate course, we will focus on using analytic models and strategies for examining data that have: 


--
- a dichotomous outcome


--
- a count outcome


--
- a nested structure


--
- missingness


--
During Unit 1, we'll also talk briefly about tools that give us information about how consistently the assessment tools we use are measuring our outcome. 


--
  + Are students with the same depression severity responding similarly to our depression scale?


--
Finally, at the end of the course, we'll spend some time critically appraising published studies that use course methods.


--
**.blue[What's the real-world applicability of the methods we'll discuss?]**

---
# Applications

- Sometimes the outcomes we're interested in don't describe a range or degree of something, like severity of depression symptoms or extent of classroom engagement. 


--
- Instead, an outcome might be the presence or the absence of a characteristic, or correspond to a state of being.


--
  + Among adolescents, is more severe depression associated with a greater likelihood of being *absent* (versus *present*) from class?


--
- Alternatively, the outcome may be a count of events over a period of time, which can also be described as a *rate*.


--
  + Among adolescents, is more severe depression associated with a *higher number of absences during the school year*?


--
**.blue[Can you think of other examples of these kinds of outcomes?]**


---
# Applications, cont.

- For either of the questions on the last slide, we would expect students to differ from one another in number of absences. But, what if the classroom that students are assigned to also makes a difference in absences? 


--
  + Perhaps some teachers are more effective than others, or students in some classes, on average, have less parental support and engagement. 


--
  + Classrooms could also differ in the number of abscences simply due to chance.


--
- In this situation, variation in absences occurs at two levels: students vary in absences, and the average number of absences in each classroom also varies. In other words, students' variation in the outcome is *nested* within variation in the outcome across classrooms. 


--
**.blue[Imagine we ran an analysis to address the question *Does depression severity predict the number of days a student is absent from class?*]**


--
**.blue[In our data, absences varied among students and also widely between classrooms, but we used an analysis that didn't differentiate those 2 levels of variation (i.e., it attributed all the variation to students). Would our results give an accurate picture of the relationship between depression and absences?]**

---
# Roadmap of EDUC 645


--
| Unit  | Week(s) | Topic
|----------------------------------------------------
| 1     | 1-3     | Outcome Types + Data Structures and Validity 
| 2     | 4-7     | Dichotomous Outcomes
| 3     | 8-10    | Count Outcomes

---
# Course activities

1. Two weekly 1.5-hour lectures will introduce concepts in interactive lectures, discussion and activities

2. Readings are intended to supplement material from lectures

3. Two *OPTIONAL, UNGRADED* weekly lab meetings intended to provide support for R programming tasks. Each lab will cover identical material.

4. Three (3) take-home quizzes worth trivial amount of points each (5% of grade)

5. Three (3) unit assignments (15% each) + final project (25% of grade)


--

<br>
[Course website](https://uo-educ-quant.github.io/645/index.html) is (we hope!) a valuable resource.


--
**.blue[Beginning Thursday, lectures will be recorded and available on the Panopto Recordings tab on Canvas.]**

---
# Concluding discussion

--
- What learning goals do you have coming into the course?


--
- Are there topics from the previous 2 courses in this sequence that still feel unclear or uncertain?


--
- What was effective or ineffective about the *structure* or *approach* of the previous courses?
