---
title: "Introduction to Nested Data"
subtitle: "EDUC 645: General Linear Model II"
author: "TBD"
#date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  xaringan::moon_reader:
    css: ['default', 'uo', 'ki-fonts', 'my_custom.css', 'xaringanthemer.css']
    # self_contained: true
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{R, setup, include = F}
library(pacman)
p_load(here, tidyverse, ggplot2, xaringan, knitr, kableExtra, foreign, broom, xaringanthemer, reshape2, DiagrammeR)

i_am("slides/EDUC645_log_regression.rmd")

extra_css <- list(
  ".red"   = list(color = "red"),
  ".blue"  =list(color = "blue"),
  ".green" = list(color = "#8bb174"),
  ".purple" = list(color = "#6A5ACD"),
  ".red-pink" = list(color= "#e64173"),
  ".grey-light" = list(color= "grey70"),
  ".slate" = list(color="#314f4f"),
  ".small" = list("font-size" = "90%"))

write_extra_css(css = extra_css, outfile = "my_custom.css")

# Knitr options
opts_chunk$set(
  comment = "#>",
  fig.align = "center",
  fig.height = 6.75,
  fig.width = 10.5,
  warning = F,
  message = F
)
opts_chunk$set(dev = "svg")
options(device = function(file, width, height) {
  svg(tempfile(), width = width, height = height)
})
options(knitr.table.format = "html")

```

# Roadmap

---
# Goals for the unit
- Introduce nested data structure (two-level, e.g., repeated measures within individuals, students within schools)
- Understand and explain what nesting/clustering means
- Demonstrate varying intercepts and slopes across clusters. 
- Practice fitting the same regression model independently for each cluster and create a table of intercepts and slopes across clusters
- Understand what it means for intercepts and slopes to vary across clusters
- Discuss the notion that regression coefficients may vary across different clusters
- Develop the concept of:
  - fixed-effects as the aggregation of the different intercepts and slopes by taking an average of varying intercept and slopes across clusters
	- random effects as the difference between cluster-specific intercept and slope and their averages across clusters
	- covariance matrix of random-effects
- Discuss the implications of ignoring the variance of random-effects in terms of the inference for fixed-effects and statistical power

- Introduce 
	- Random intercept-only model
	  - its estimation through the R lmer package, 
		- interpret the model parameters and align them with the earlier discussion of fixed-effects and random-effects.
	- Intra-class correlation as a measure of within-cluster dependency
and how to use it to decide whether one needs to use multilevel modeling

---
# What is Nested Data?

---
# Where does it come from?
### Why do we need to think hierarchically?
1) Two realities exist within interventions:
  (a) Effect implies change in individuals over time,
  (b) Effect occurs in groups and organizational settings (e.g., dyads, groups, networks, neighborhoods, clinics, cities, countries).

2) Factors are nested across multiple levels; influence the organization of behavior.

---
# What happens if we ignore it?

### What errors result if we ignore multilevel effects?
#### Ecological Fallacy
- Systematic underestimation of group effects
- Inadequate intervention development and evaluation
#### Aggregation bias
- Attribute that an individual-level indicator is representative of the entire group
#### Biased estimation of statistical associations
- Misestimated standard errors
- Homogeneity of regression slopes

---
# Traditional Linear Regression Example
! Unit of analysis: Individual
! Examine between-individual variability
! Intercept and slope are the same for all groups
! Ignores inclusion of important group variables
! Residual correlation

---
# What does “independence” mean?
#### The observation of one participant does not depend on the response of other participants
#### What happens to independence when:
- We collect data across multiple sites?
- Collect observations from the same individual over time?

---
# Intraclass Correlation
### Intraclass correlation: Proportion of total variability in the outcome that occurs between groups.
### The greater the intraclass correlation (ICC), the greater the reflection of inequality between groups.

---
# Intraclass Correlation
### How have we commonly taken care of the ICC “issue”?
- Ecologic Regression
- Stratified Regressions
- Group fixed-effects Model
- Contextual Model
- Hierarchical Linear Models
### Group-level modeling
### Repeated-measured modeling (“Growth curves”)

---
# Multilevel Models (MLM)
! Units of analysis: Individual and Group
! Examine between-individual and between-group variability
! The intercept and slopes may be different for individuals within and across groups
! These differences may be explained by cross-level interactions (differential effects due to individual and group-level characteristics)
! Allows for the inclusion of important individual and group variables
! No residual correlation

---
# Sampling and Design Considerations
### Formulating Research Questions
#### Several questions may be proposed and result in different multilevel equations:
- What is the association between UVI and number of partners among women in PR, after adjusting for clustering effects?
- Is there an association between UVI and living in a city where female condoms (FCs) are free and accessible?
- Do characteristics pertaining to a city modify the association between UVI and number of partners?

---
# Sampling and Design Considerations
### Design
#### What constitutes a group-level variable?
- Characteristic of an individual (provider, partner)
- Characteristic of a setting (number of beds in hospital, allocated budget for HIV prevention in an agency)
- Characteristics of catchment areas (Census, DHS)
- Policies (% of budget allocated to abstinence-only)
#### How are group-level variables defined?
- Aggregating individual-level characteristics into groups
(neighborhood SES)
- Developing group-level measures (AIDS stigma in a
neighborhood)

---
# Sampling and Design Considerations
### Sampling
#### Calculating Statistical Power is similar to “traditional” analyses
- Formulate the hypotheses to be tested
- Compute or Estimate the ICC
- Determine the variable and outcome of interest
- Determine the sample frame based on the I.V.(s)

#### Sampling clusters or sampling individuals?
- Determine the number of parameters in the model
- Calculate the number of observations needed for each cluster

#### Law of Diminishing Returns

---
# Nested and crossed random effects in "lme4"

---
# Summary
### Multilevel Modeling allows us to answer complex questions adequately if:
- An appropriate study design is conceptualized
- Measures across levels are identified from existing datasets and/or operationalized carefully

### Multilevel Modeling may be appropriate if residual correlations exist due to violations of independence
- Benefit of partitioning variance even when Level-1 or Level-2 variables will not be modeled