---
title: "EDUC 645 Schedule"
site: distill::distill_website
output:
  html_document:
    toc: yes
    toc_depth: 3
    toc_float: yes
    theme: cosmo
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Unit 1: Dichotomous Outcomes

**Learning Objectives:** 

- Describe the linear probability model and discuss its limitations

- Differentiate between the concepts of probability, odds, and logit

- Estimate and interpret model parameters logistic regression model with continuous and categorical predictors

- Discuss predictive power, model fit, and diagnostics for logistic regression models

**Readings**:

 * BMLR Chapter
 * Mood, C. (2010). Logistic regression: Why we cannot do what we think we can do, and what we can do about it. *European Sociological Review*, 26(1), 67-82. 861-874.[https://doi-org.libproxy.uoregon.edu/10.1093/esr/jcp006](https://www.jstor.org/stable/40602478)

**Lecture**:

 * Lecture slides: [html](./slides/EDUC645_log_regression.html)
 * Dataset: [principal.csv](./data/principal.csv)

**Assignment**:

 * Assignment description: [assignment1.html](./assignments/assignment1.html)
 * Dataset: [nscs.csv](./data/nscs.csv)

## Unit 2: Count Outcomes

**Learning Objectives:** 

- Apply regression models to analyze count and rates as outcome variables

-	Describe situations which merit the use of Poisson regression

-	State the assumptions about rates in Poisson regression

- Use Poisson regression model with continuous and categorical predictors, and interpret the model parameters and inference for model parameters

- Evaluate dispersion of the outcome variable, model fit, and diagnostics for a Poisson regression model

**Readings**: 

 * BMLR Chapter
 * Coxe, S., West, S. G., & Aiken, L. S. (2009). The analysis of count data: A gentle introduction to Poisson regression and its alternatives. *Journal of Personality Assessment*, 91(2), 121-136. [https://doi.org/10.1080/00223890802634175](https://doi-org.libproxy.uoregon.edu/10.1080/00223890802634175)
 
**Lecture**:

 * Lecture slides: [html](./slides/EDUC645_poisson_regression.html)
 * Dataset: [ceps_sch.csv](./data/ceps_sch.csv)

**Assignment**:

 * Assignment description: [assignment2.html](./assignments/assignment2.html)
 * Dataset: [ah_smoke.csv](./data/ah_smoke.csv)


## Unit 3: Nested Data Structures

**Learning Objectives:** 

- Describe nested data structures (two-level, e.g., repeated measures within individuals, students within schools)

- Demonstrate how intercepts, slopes, and regression coefficients may vary across clusters

- Compare and contrast using fixed-effects and random-effects in regression models

- Explain the covariance matrix of random-effects and describe implications of ignoring random-effects in terms of the inference for fixed-effects and statistical power

- Measure within-cluster dependency using intra-class correlation, and describe how to evaluate whether multilevel modeling is appropriate

- Create fixed and random intercept-only models and interpret the model parameters using the R `lmer` package

- *Time permitting*: Discuss alternatives to multilevel modeling of nested data

**Readings**: 
 
 * BMLR Chapter
 
**Lecture**:

 * Lecture slides: [html](./slides/EDUC645_nested_data.html)
 * Dataset: [seda.csv](./data/seda.csv) and [portugal.csv](./data/portugal.csv)

**Assignment**:

 * Assignment description: [assignment3.html](./assignments/assignment3.html)
 * Dataset: [gpa.csv](./data/gpa.csv) / [gpa_above.csv](./data/gpa_above.csv)


## Unit 4: Measurement and Assessment

**Learning Objectives:** 

- Differentiate and define different aspects of measurement and understand when they apply

- Demonstrate how to compute and interpret Cronbach's alpha

- Define the assumptions and limitations for methods to assess reliability

**Readings**: 

 * BMLR Chapter
 * IEPM Chapter

**Lecture**:

 * Lecture slides: [html](./slides/EDUC645_measure_assess.html)
 * Dataset:
 
**Assignment**:

 * Assignment description: [assignment4.html](./assignments/assignment4.html)
 * Dataset: 

## Unit 5: Missing Data

**Learning Objectives:** 

- Discuss the concept of model-based imputation in the context of linear regression, logistic regression, and Poisson regression models

- Identify and describe missing data mechanisms

- Differentiate listwise and pairwise deletion methods from single-imputation methods

- Describe the "missing-value-dummy" method (Cohen) and some issues with this approach

- Compare and contrast the conceptual steps for the multiple-imputation with using full-information maximum likelihood estimators to account for missing data

- Using the R `mice` package to practice applying multiple-imputation to fit linear, logistic, and Poisson regression models for a data set with missing values


**Readings**: 

  * Baraldi, A. N., & Enders, C. K. (2010). An introduction to modern missing data analyses. *Journal of School Psychology*, 48(1), 5-37. [https://doi.org/10.1016/j.jsp.2009.10.001](https://pubmed.ncbi.nlm.nih.gov/20006986/)

**Lecture**:

 * Lecture slides: [html](./slides/EDUC645_cleaning_missing.html)
 * Dataset: [galo.csv](./data/galo.csv)
 
**Assignment**:

No assignment for this unit.

**Final Project**:

 * Final project description: [final.html](./assignments/final.html)
 * Dataset: 

