---
title: "EDUC 645 Assignment 2"
subtitle: "Unit 2: Count Outcomes and Poisson Regression"
output: html_document
---

#### Submission Deadline

May 12 (11:59 PM)

#### Submission Format

You are required to submit the following files:  

 * .doc, .html, or .pdf file with your typed responses to the problems and any tables and figures you produce. 
 * If you used R to create tables and/or figures in the above doc/html/pdf file, you must also submit the .Rmd or .R file you used to render the tables and figures. 
 
#### Background and Dataset

Educational attainment is generally lower for people with limited economic resources and social capital. Compared with college graduates, individuals who have not graduated high school or obtained a college degree are more likely to experience poorer physical and mental health outcomes. Opportunities that can be afforded by post-secondary education – including higher income, greater economic stability, and improved quality of life – may directly influence health outcomes by increasing access to preventative health care and reducing life stress and exposure to unhealthy environmental conditions, among other mechanisms. See [Duncan 2017](https://uo-educ-quant.github.io/645/articles/Duncan_2017.pdf), [Friesen 2022](https://uo-educ-quant.github.io/645/articles/Friesen_2022.pdf), and [Hair 2015](https://uo-educ-quant.github.io/645/articles/Hair_2015.pdf) for further discussion. 

[Case and Deaton](https://uo-educ-quant.github.io/645/articles/Case_Deaton_2017.pdf) have proposed that multigenerational economic and social disadvantage also have indirect effects on health and mortality by creating environments that are hostile to economic advancement, social connectedness, and socioemotional wellbeing. These conditions, they argue, result in the marked increase in overdoses, suicides, and alcohol-related mortality among adults with low educational attainment – outcomes they describe as *deaths of despair*.

A number of studies have found greater burden of alcohol misuse among those with lower socioeconomic status [see Probst et al 2015 for a review](https://uo-educ-quant.github.io/645/articles/Probst_2015.pdf). At the same time, some research (e.g., [Assari and Lankarani, 2017](https://uo-educ-quant.github.io/645/articles/Assari_Lankarani_2017.pdf)) has suggested that college-educated adults have higher rates of alcohol use than adults with lower educational attainment, potentially due to greater availability of financial and other resources that enable more frequent drinking. 

Download the assignment dataset [here](https://uo-educ-quant.github.io/645/data/NHANES_data_Assign2.RData). These data are from the 2011-12 NHANES survey. For our purposes, we will use a simplified version of the dataset that can be treated like a simple random sample of the US population. The following variables are of interest:

 * `AlcoholYear`: Estimated number of days over the preceding year that a study participant drank alcoholic beverages. Reported for participants aged 18 years or older.
 * `Education_level`: Educational level of study participant: `High school or less` (i.e., no college degree) or `Graduated college`  Reported for participants aged 20 years or older.
 * `Age`: Age in years at screening of study participant.
 * `Sex`: Assigned sex of study participant (`Male` or `Female`).

#### Assignment Requirements

The goal of this assignment is to examine whether there is a relationship between educational attainment (independent variable) and alcohol use frequency (number of drinking days in the preceding year; dependent variable) among NHANES participants - and if so, whether the relationship is consistent with prior research. 

**Your submission should include the following elements (% weight for grading):**

1. Research significance (10%) 
    + Read over the studies and literature reviews linked in the first and third paragraphs of the background section, and other relevant studies you might identify, and provide a 1-2 paragraph summary of existing evidence on the relationship between educational attainment and alcohol use. 
    + After reviewing the available evidence, restate the research question in your own words. 

2. Analytic sample summary statistics (10%)
    + Load the dataset and perform basic data management.
      + Because education level was only assessed in participants 20 years or older, delete observations from participants under 20 at the time of the assessment.  
      + Check whether the variables are the right class: dichotomous independent variables should be *factors*, and continuous and count variables should be *numeric* (num) or *integers* (int). If not, convert them to the right type. Also check that factor levels are in the preferred order for analysis. 
    + Produce a summary statistics table (Table 1), including medians of continuous and count variables and proportions of categorical variables.
    + Write a short paragraph describing the sample, key variables, and the summary statistics.
 
3. Methods and analysis (50%)
    + Model the relationship between education level and the number of days that participants drank alcohol in the preceding year.
      + Compare Poisson and negative binomial models (with `Education_level` as the only independent variable) and select the best-fitting model type. 
      + Once you have selected a model type, fit and compare alternative models with age, and age and sex, included as covariates. 
      + Then, explore an interaction between sex and education level, given research that suggests alcohol use and related outcomes can differ by sex. 
      + Check for critical assumptions and outliers of the best-fitting model.
    + Write a paragraph describing your model selection process and diagnostics results.
    + Write a paragraph stating the results of your best-fitting model (including predicted counts).
    + Produce a results table (Table 2) that includes the model results and model fit statistics. 
    + If the interaction is significant, include a plot (Figure 1) of predicted counts to facilitate interpretation. 


4. Discussion and conclusions (20%)
    + Write 1-2 paragraphs summarizing your results, describing whether (and to what extent) the results address your research question, and relating your findings back to the broader evidence base. 
    + Describe potential limitations of your methods, including the use of cross-sectional data to examine the association between educational attainment and alcohol use. If the test for zero inflation was significant, discuss potential reasons why there might be an excessive amount of zero counts in the data. 


5. References, tables, and figures (10%)
    + Must include references, Table 1, and Table 2. Figure 1 should be included if interaction is significant. 
    + Other tables and figures you think are helpful.


