---
title: "EDUC 645 Assignment 1"
subtitle: "(Unit 1: Logistic Regression)"
output: html_document
---

#### Submission deadline

TBD

#### Submission format

You are required to submit two files:  

 - An .doc, .html, or .pdf file that includes your typed responses (in your own words and not identical to anybody else's), tables, and/or figures to the problems  
 - The .Rmd or .R file that you used to render the tables and figures in the above doc/html/pdf file. 
 
#### Dataset

(Download the dataset here: [nscs.csv](./data/nscs.csv))

To gain a broad picture of the counselor experience during the early months of COVID-19 school closures, Savitz-Romer and Rowan-Kenyon (2021) created an 80-question online survey to collect data from 1,060 school counselors and educators in adjacent roles (e.g., college counselors, adjustment counselors, counseling directors) in 48 states and Puerto Rico in the US. For simplicity reasons, in our dataset, we only include key variables as following and keep only complete observations (N = 787):

 - id, counselor identification number
 - grades, school level, 0 = elementary, 1 = middle school, 2 = high school, 3 = mixed
 - schooltype, school type, 1 = public, 2 = charter, 3 = private
 - urbanicity, school urbanicity level, 1 = urban, 2 = suburban, 3 = rural
 - female, counselor gender coded one for female and zero for others
 - exp, counselor experience measured by years
 - ooo, dichotomous variable coded one if the counselor had less time for one-on-one counseling due to COVID 
 - group, dichotomous variable coded one if the counselor had less time for group counseling due to COVID 
 - sel, dichotomous variable coded one if the counselor had less time for supporting student social emotional needs due to COVID 


#### Assignment requirements

You're interested in *which counselor or school characteristic is significantly associated with reduced counseling service during the early stage of COVID pandemic*. Your assignment will be graded based on the following components:

1. Research significance (10% points) 

    + Conduct a brief literature review on how the pandemic impacted school counseling programming, with a focus on which counselor characteristic (gender OR years of experience) or school characteristic (school level OR type OR urbanicity) was significantly associated with reduced counseling services (one-on-one counseling OR group counseling OR supporting student social emotional needs).     + Based on your research, identify a research question that uses one of the three "reduced counseling services" measures as outcome variable.
    + Write up your reasoning in a short paragraph that is ended with your specified research question.  

2. Analytic sample summary statistics (10% points)

    + Load the dataset and perform basic data management
      + only keep variables that you think will be used in your analysis and drop other variables
      + drop incomplete observations
      + check whether your variables are the right class (e.g., you want id and school variables to be factor rather than double), if not, convert them to the right type
      + other data management you think fit 
    + Produce a summary statistics table (Table 1)
    + Write a short paragraph describe your sample, key variables, and the summary statistics
 
3. Methods and analysis (30% points)

    + Model the relationship of your interest in a linear probability model
      + add covariates and see if your estimates change
    + Model this relationship in a logistic regression model
      + add covariates and see if your estimates change
    + Write a short paragraph to report the results of each model you fit

4. Logistic regression assumptions and diagnostics (10% points)

    + Check for critical assumptions and outliers
      + supply with plots if necessary
    + Write a short paragraph to report your diagnostics tests

5. Discussions and conclusions (30% points)

    + Put all of your models in a table (Table 2) 
    + Write a short paragraph to compare the models, summarize your findings, and answer your research question

6. References, tables, and figures (10% points)

    + Must include references, Table 1, Tabl 2
    + Other tables and figures you see fit
