---
title: "EDUC 645 Assignment 3"
subtitle: "(Unit 3: Nested data)"
output: html_document
---

#### Submission deadline

TBD

#### Submission format

You are required to submit two files:  

 - An .doc, .html, or .pdf file that includes your typed responses (in your own words and not identical to anybody else's), tables, and/or figures to the problems  
 - The .Rmd or .R file that you used to render the tables and figures in the above doc/html/pdf file. 
 
#### Dataset

The GPA data is a longitudinal dataset, where 200 college students were followed for six consecutive semesters. The data was simulated. Key variables are detailed below.

 - stuid, student identification number
 - time, a factor variable indexing the six consecutive semesters
 - gpa, student's GPA at the end of semester
 - gpa_above, coded one if student's end of semester GPA is above 3.0 and zero otherwise
 - female, a dichotomous variable coded one for female students and zero for male
 - hsgpa, high school GPA
 
Download the dataset [here](./data/gpa.csv)

#### Assignment requirements

You are interested in investigating whether and how the relationship between high school GPA and college GPA changes over time (six semesters). Note that you can choose your outcome variable from a continuous measure of end of semester GPA (gpa) and a dichotomous measure of end of semester GPA (gpa_above), but your predictor variable is high school GPA (hsgpa). You are encouraged to conduct a brief literature review before developing your own research question and hypothesis. Then draw variables that are essential to your own analysis and drop incomplete observations in your own analytic sample.

Your assignment will be graded based on the following components:

1. Research significance (10% points) 

    + Conduct a brief literature review and develop your research question based on the data availability of the dataset.
    + Write up your reasoning in a short paragraph that is ended with your specified research question.  

2. Analytic sample summary statistics (10% points)

    + Load the dataset and perform basic data management
      + only keep variables that you think will be used in your analysis and drop other variables
      + drop incomplete observations
      + check whether your variables are the right class, if not, convert them to the right type
      + other data management you think fit 
    + Produce a summary statistics table (Table 1)
    + Write a short paragraph describe your sample, key variables, and the summary statistics
 
3. Methods and analysis (30% points)

    + Model the relationship of your interest in a series of mixed-effects models such as following:
      + fixed-effects only model (traditional OLS)
      + allow the intercept to vary by semester but not slope (random intercept)
      + allow both the intercept and slope to vary by semester (random intercept and slope)
      + any models you see can provide you new perspectives on your research question
    + Write a short paragraph to report the results of each model you fit

4. Poisson regression assumptions and diagnostics (10% points)

    + Calculate and report the ICC to see if random-effects modeling is appropriate
    + Check for critical assumptions
       + supply with plots if necessary
    + Write a short paragraph to report your diagnostics tests

5. Discussions and conclusions (30% points)

    + Put all of your models in a table (Table 2) 
    + Write a short paragraph to compare the models (provide evidence on model fit), summarize your findings, and answer your research question

6. References, tables, and figures (10% points)

    + Must include references, Table 1, Tabl 2
    + Other tables and figures you see fit
