---
title: "EDUC 645 Final Project"
output: html_document
---

### General guidelines

The purpose of this final project is to practice the statistical concepts and data analysis techniques we’ve learned during this entire term. 

You may work on your own or collaborate with one partner. Please make sure that you engage in a a full, fair and mutually-agreeable collaboration if you do choose to collaborate. If you do collaborate, you should plan, execute and write-up your analyses together, not simply divide the work. Please make sure to indicate clearly when your work is joint and any other individual or resource (outside of class material) you consulted in your responses.

### Project options

Based on your own research interest, choose one from the following.
 
#### 1. Final project option 1 (Add Health longitudinal data)

(Download the datasets here: [add_health.csv](./data/add_health.csv))

### add_health.csv

This dataset is drawn from the first, third, and fourth waves of National Longitudinal Study of Adolescent to Adult Health ([Add Health](https://addhealth.cpc.unc.edu/data/#public-use)) data. Add Health is a longitudinal study of a nationally representative sample of over 20,000 adolescents who were aged from 12-20 during the first wave (1995) and aged from 18-26 and from 24-32 when the third (2001) and fourth (2008) waves took place. Add Health data contains rich demographic, social, familial, socioeconomic, behavioral, psychosocial, cognitive, and health information on adolescents as well as their adulthood and is examined in a wide range of [social science studies](https://addhealth.cpc.unc.edu/publications/). 

Note that the public-use data sample is much smaller in size and matching three waves resulted in 3,442 total observations in our dataset.

**Predictor variables and covariates from wave 1:**

 - *id*, the individual's identifier
 - *grade*, factor variable indicating the individual's grade (7, 8, 9, 10, 11, or 12)
 - *female*, dummy variable coded one for individuals whose biological sex is female
 - *age*, the individual's age in wave 1
 - *hispanic*, *white*, *black*, *native*, and *asian* are all dummy variables coded one for individuals whose self-identified race is Hispanic or Latino, White, Black or African American, American Indian or Native American, and Asian or Pacific Islander, respectively
 - *prtedu* represents the highest years of education of the individual's household mother and father. 
 - *health*, the individual's self-report health status; 4=excellent, 3=very good, 2=good, 1=fair, 0=poor
 - *sleepenough*, the individual's self-report rating of whether they get enough sleep; 0=never, 1=just a few times, 2=about once a week, 3=almost every day, 4=every day
 - *eversmoke*, dummy variable coded one for individuals who ever smoked
 - *repeating*, dummy variable coded one for individuals who ever repeated a grade
 - *skipping*, dummy variable coded one for individuals who ever skipped a grade
 - *oos*, dummy variable coded one for individuals who got at least one out-of-school suspension
 - *expelled*, dummy variable coded one for individuals who were ever expelled
 - *tsr* and *ssr* measure the individual's self-rating on the questions "Are you getting along with your teachers?" and "Are you getting along with other students?"; 0=never, 1=just a few times, 2=about once a week, 3=almost everyday, 4=everyday
 
**Outcome variables from waves 3 and 4:**

 - *gpa*, the individual's high school final GPA points
 - *education*, the individual's total years of education. 
 - *income_log*, the individual's log-transformed annual earnings 
 - *jail*, number of times the individual being arrested since 18th birthday
 - *suicidethought*, dummy variable coded one for individuals who had ever seriously thought about committing suicide during the past 12 months by the time of survey
 - *q1* to *q8*, eight survey questions measured on a four-point likert-scale, detailed below:
 
   - Survey questions: Think about the past seven days. How often was each of the following things true during the past seven days?
     - *q1*, "You were bothered by things that usually don't bother you."
     - *q2*, "How often do you feel isolated from others?"
     - *q3*, "You had trouble keeping your mind on what you were doing."
     - *q4*, "You felt depressed."
     - *q5*, "You felt happy."
     - *q6*, "You enjoyed life."
     - *q7*, "You felt sad."
     - *q8*, "You felt that people disliked you."

   - Levels:
     - 0 = Never,
     - 1 = Sometimes,
     - 2 = A lot of the time
     - 3 = Most of the time or all of the time

**Tasks**

1). Logistic regression: using *suicidethought* as outcome variable and one of the wave 1 predictor variables to construct your research question (add covariates as you see fit to check the robustness of your results)

2). Poisson regression: using one of the happiness measures (*q1* to *q8*) as outcome variable and one of the wave 1 predictor variables to construct your research question (add covariates as you see fit to check the robustness of your results); also test for over dispersion before conducting analyses to make sure that using Poisson regression is appropriate

3). Nested data: using one of the three variables, *gpa*, *education*, *income_log*, as outcome variable and one of the wave 1 predictor variables to construct your research question (add covariates as you see fit to check the robustness of your results)

4). Measurement and assessment: test and report the internal consistency for the eight measures of happiness (*q1* to *q8*)

5). Dealing with missing data in your analyses

#### 2. Final project option 2 (FSI assessment data)

Dynamic Indicators of Basic Early Literacy Skills (DIBELS) is a set of procedures and measures for assessing the acquisition of literacy skills. They are designed to be short (one minute) fluency measures that can be used to regularly detect risk and monitor the development of early literacy and early reading skills in kindergarten through eighth grade. Researchers at UO began work on DIBELS 8th Edition in 2016 and over the course of three years have been hard at work making the 8th Edition of DIBELS better than any previous DIBELS edition. Our dataset is drawn from DIBELS 8th Edition user database and focus on a small sample of kindergarten kids (N = 128) from 4 schools, 8 classrooms. It contains 32 variables including student raw scores on First Sound Isolation (FSI) measures as well as school and classroom demographics, detailed below.

 - *id*, student identifier
 - *school*, school identifier
 - *classroom*, classroom identifier
 - *fsi_b01* to *fsi_b20* are student raw scores on isolating first sound of 20 words (he, off, toe, is, pay, up, my, at, fin, egg, bad, rock, zip, nose, sat, kids, dance, gold, vans, lips). For the first ten words, each score is measured on a binary scale: 0 = incorrect, 2 = correct. For the remaining ten words, each score is measured on a three-point likert scale: 0 = incorrect, 1 = somehow correct, 2 = correct. Scoring rubric is available upon request.
 - *total*, student's total FSI score
 - *locale*, nominal measure of school location
 - *class_size*, classroom size
 - *avg_age*, classroom average age in month
 - *pct_female*, classroom percentage of female students
 - *pct_sped*, classroom percentage of sped students
 - *pct_white*, classroom percentage of white students
 - *pct_black*, classroom percentage of African American students
 - *pct_hispanic*, classroom percentage of Hispanic and Latino students

(Download the datasets here: [fsi.csv](./data/fsi.csv))


### Project requirements

Your final project will have FOUR chapters to address the first four tasks detailed at the end of your selected project. 

For each chapter, the writeup should contain the following elements:

 - What is the research question? What is its research significance?  
 - Describe your sample and key variables. Present the summary statistics of your key variables, especially the predictor and outcome variables, in a table
 - Visualize the relationship between the predictor and outcome variables in a plot and describe what you observe
 - Describe your method, report your results, and discuss your findings


### Submission timeline

You have three critical deadlines to meet in order to successfully finish this final project:

 - During week 5 lab, briefly (within 1 minute) present to the class the dataset you'll be using and your research questions
 - During week 8 lab, briefly (within 1 minute) present to the class the methods you'll be using to answer your research questions including assumptions and model specifications
 - At the end of the term (date: TBD), submit two files to Canvas:
   - An .doc, .html, or .pdf file that meets the project requirements above
   - The .Rmd or .R file that you used to render the tables and figures in the above doc/html/pdf file
 